export { default as LoginPage } from './pages/LoginPage'
export { default as RegisterPage } from './pages/RegisterPage'
export { default as EmailVerificationPage } from './pages/EmailVerificationPage'
export { default as SuccessfulVerificationPage } from './pages/SuccessfulVerificationPage'
export { default as AccountDetailsPage } from './pages/AccountDetailsPage'